apiVersion: v1
kind: Pod
metadata:
  name: busybox-demo
  namespace: default
spec:
  imagePullSecrets: 
  #secret to login private docker registry
  - name: registry-pull-secret
  containers:
  - name: busybox-demo
    # image: registry.cn-beijing.aliyuncs.com/ducafe/busybox:1.24
    image: registry.cn-beijing.aliyuncs.com/kube-systems/busybox-demo:1.24
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always